version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: Password01
      POSTGRES_DB: bilby
    ports:
      - 5432:5432
    volumes:
      - dbvolume:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 8888:8080

  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    volumes:
      - blobvolume:/data

# docker volume create bilby.postgres.data
# docker volume create bilby.blobstorage.data
volumes:
  dbvolume:
    external: true
    name: bilby.postgres.data
  blobvolume:
    external: true
    name: bilby.blobstorage.data
